# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfaceYsXAlw.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QToolBar, QToolBox, QVBoxLayout,
    QWidget)
import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1135, 847)
        palette = QPalette()
        gradient = QLinearGradient(0, 0, 1, 1)
        gradient.setSpread(QGradient.PadSpread)
        gradient.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(72, 84, 97, 255))
        gradient.setColorAt(1, QColor(40, 49, 59, 255))
        brush = QBrush(gradient)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        gradient1 = QLinearGradient(0, 0, 1, 1)
        gradient1.setSpread(QGradient.PadSpread)
        gradient1.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(72, 84, 97, 255))
        gradient1.setColorAt(1, QColor(40, 49, 59, 255))
        brush1 = QBrush(gradient1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        gradient2 = QLinearGradient(0, 0, 1, 1)
        gradient2.setSpread(QGradient.PadSpread)
        gradient2.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(72, 84, 97, 255))
        gradient2.setColorAt(1, QColor(40, 49, 59, 255))
        brush2 = QBrush(gradient2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush2)
        gradient3 = QLinearGradient(0, 0, 1, 1)
        gradient3.setSpread(QGradient.PadSpread)
        gradient3.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(72, 84, 97, 255))
        gradient3.setColorAt(1, QColor(40, 49, 59, 255))
        brush3 = QBrush(gradient3)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        gradient4 = QLinearGradient(0, 0, 1, 1)
        gradient4.setSpread(QGradient.PadSpread)
        gradient4.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(72, 84, 97, 255))
        gradient4.setColorAt(1, QColor(40, 49, 59, 255))
        brush4 = QBrush(gradient4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        gradient5 = QLinearGradient(0, 0, 1, 1)
        gradient5.setSpread(QGradient.PadSpread)
        gradient5.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(72, 84, 97, 255))
        gradient5.setColorAt(1, QColor(40, 49, 59, 255))
        brush5 = QBrush(gradient5)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        gradient6 = QLinearGradient(0, 0, 1, 1)
        gradient6.setSpread(QGradient.PadSpread)
        gradient6.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(72, 84, 97, 255))
        gradient6.setColorAt(1, QColor(40, 49, 59, 255))
        brush6 = QBrush(gradient6)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        gradient7 = QLinearGradient(0, 0, 1, 1)
        gradient7.setSpread(QGradient.PadSpread)
        gradient7.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(72, 84, 97, 255))
        gradient7.setColorAt(1, QColor(40, 49, 59, 255))
        brush7 = QBrush(gradient7)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        gradient8 = QLinearGradient(0, 0, 1, 1)
        gradient8.setSpread(QGradient.PadSpread)
        gradient8.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(72, 84, 97, 255))
        gradient8.setColorAt(1, QColor(40, 49, 59, 255))
        brush8 = QBrush(gradient8)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet(u"QMainWindow,QMenuBar,QToolBar{\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #485461, stop:1 #28313b);\n"
"}\n"
"#centralwidget{\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #485461, stop:1 #28313b);	\n"
"}\n"
"QDockWidget {\n"
"	border: 2px solid #403F3F;\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #485461, stop:1 #28313b);\n"
"}\n"
"QMenuBar {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #485461, stop:1 #28313b);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent; /* Men\u00fc \u00f6\u011fesi arkaplan rengi \u015feffaf */\n"
"    color: white; /* Men\u00fc \u00f6\u011fesi metin rengi */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.actionA = QAction(MainWindow)
        self.actionA.setObjectName(u"actionA")
        icon = QIcon()
        icon.addFile(u":/icons/icons/file-plus.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionA.setIcon(icon)
        self.actionA_2 = QAction(MainWindow)
        self.actionA_2.setObjectName(u"actionA_2")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/folder-plus.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionA_2.setIcon(icon1)
        self.actionSon_Dosyalar = QAction(MainWindow)
        self.actionSon_Dosyalar.setObjectName(u"actionSon_Dosyalar")
        self.actionLKaydet = QAction(MainWindow)
        self.actionLKaydet.setObjectName(u"actionLKaydet")
        self.actionFarkl_Kaydet = QAction(MainWindow)
        self.actionFarkl_Kaydet.setObjectName(u"actionFarkl_Kaydet")
        self.actionYazd_r = QAction(MainWindow)
        self.actionYazd_r.setObjectName(u"actionYazd_r")
        self.actionResmi_Kaydet = QAction(MainWindow)
        self.actionResmi_Kaydet.setObjectName(u"actionResmi_Kaydet")
        self.actionKapat = QAction(MainWindow)
        self.actionKapat.setObjectName(u"actionKapat")
        self.action_k = QAction(MainWindow)
        self.action_k.setObjectName(u"action_k")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionNew.setIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/folder.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/save.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSend_Back = QAction(MainWindow)
        self.actionSend_Back.setObjectName(u"actionSend_Back")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/upload.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSend_Back.setIcon(icon4)
        self.actionBring_Front = QAction(MainWindow)
        self.actionBring_Front.setObjectName(u"actionBring_Front")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/download.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBring_Front.setIcon(icon5)
        self.actionTarama = QAction(MainWindow)
        self.actionTarama.setObjectName(u"actionTarama")
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/disc.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTarama.setIcon(icon6)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        font = QFont()
        font.setBold(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet(u"")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(40, 60, 850, 650))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1135, 22))
        palette1 = QPalette()
        gradient9 = QLinearGradient(0, 0, 1, 1)
        gradient9.setSpread(QGradient.PadSpread)
        gradient9.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient9.setColorAt(0, QColor(72, 84, 97, 255))
        gradient9.setColorAt(1, QColor(40, 49, 59, 255))
        brush9 = QBrush(gradient9)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush9)
        gradient10 = QLinearGradient(0, 0, 1, 1)
        gradient10.setSpread(QGradient.PadSpread)
        gradient10.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient10.setColorAt(0, QColor(72, 84, 97, 255))
        gradient10.setColorAt(1, QColor(40, 49, 59, 255))
        brush10 = QBrush(gradient10)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush10)
        gradient11 = QLinearGradient(0, 0, 1, 1)
        gradient11.setSpread(QGradient.PadSpread)
        gradient11.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient11.setColorAt(0, QColor(72, 84, 97, 255))
        gradient11.setColorAt(1, QColor(40, 49, 59, 255))
        brush11 = QBrush(gradient11)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush11)
        gradient12 = QLinearGradient(0, 0, 1, 1)
        gradient12.setSpread(QGradient.PadSpread)
        gradient12.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient12.setColorAt(0, QColor(72, 84, 97, 255))
        gradient12.setColorAt(1, QColor(40, 49, 59, 255))
        brush12 = QBrush(gradient12)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        gradient13 = QLinearGradient(0, 0, 1, 1)
        gradient13.setSpread(QGradient.PadSpread)
        gradient13.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient13.setColorAt(0, QColor(72, 84, 97, 255))
        gradient13.setColorAt(1, QColor(40, 49, 59, 255))
        brush13 = QBrush(gradient13)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        gradient14 = QLinearGradient(0, 0, 1, 1)
        gradient14.setSpread(QGradient.PadSpread)
        gradient14.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient14.setColorAt(0, QColor(72, 84, 97, 255))
        gradient14.setColorAt(1, QColor(40, 49, 59, 255))
        brush14 = QBrush(gradient14)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        gradient15 = QLinearGradient(0, 0, 1, 1)
        gradient15.setSpread(QGradient.PadSpread)
        gradient15.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient15.setColorAt(0, QColor(72, 84, 97, 255))
        gradient15.setColorAt(1, QColor(40, 49, 59, 255))
        brush15 = QBrush(gradient15)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush15)
        gradient16 = QLinearGradient(0, 0, 1, 1)
        gradient16.setSpread(QGradient.PadSpread)
        gradient16.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient16.setColorAt(0, QColor(72, 84, 97, 255))
        gradient16.setColorAt(1, QColor(40, 49, 59, 255))
        brush16 = QBrush(gradient16)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush16)
        gradient17 = QLinearGradient(0, 0, 1, 1)
        gradient17.setSpread(QGradient.PadSpread)
        gradient17.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient17.setColorAt(0, QColor(72, 84, 97, 255))
        gradient17.setColorAt(1, QColor(40, 49, 59, 255))
        brush17 = QBrush(gradient17)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush17)
        self.menuBar.setPalette(palette1)
        font1 = QFont()
        font1.setBold(True)
        self.menuBar.setFont(font1)
        self.menuDosya = QMenu(self.menuBar)
        self.menuDosya.setObjectName(u"menuDosya")
        palette2 = QPalette()
        self.menuDosya.setPalette(palette2)
        self.menuD_zenle = QMenu(self.menuBar)
        self.menuD_zenle.setObjectName(u"menuD_zenle")
        self.menuAyarlar = QMenu(self.menuBar)
        self.menuAyarlar.setObjectName(u"menuAyarlar")
        palette3 = QPalette()
        self.menuAyarlar.setPalette(palette3)
        self.menuPencere = QMenu(self.menuBar)
        self.menuPencere.setObjectName(u"menuPencere")
        MainWindow.setMenuBar(self.menuBar)
        self.DosyaToolBar = QToolBar(MainWindow)
        self.DosyaToolBar.setObjectName(u"DosyaToolBar")
        self.DosyaToolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.DosyaToolBar)
        self.DosyaToolBar_2 = QToolBar(MainWindow)
        self.DosyaToolBar_2.setObjectName(u"DosyaToolBar_2")
        self.DosyaToolBar_2.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.DosyaToolBar_2)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setFont(font1)
        self.dockWidget.setStyleSheet(u"QDockWidget {\n"
"    border: 2px solid transparent; \n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #485461, stop:1 #28313b);\n"
"    color: White;\n"
"}\n"
"\n"
"")
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widget = QWidget(self.dockWidgetContents)
        self.widget.setObjectName(u"widget")
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setClearButtonEnabled(False)

        self.verticalLayout_2.addWidget(self.lineEdit)

        self.toolBox = QToolBox(self.widget)
        self.toolBox.setObjectName(u"toolBox")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 133, 643))
        self.verticalLayout_3 = QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")

        self.verticalLayout_3.addWidget(self.label)

        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout_3.addWidget(self.label_2)

        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon7.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Normal, QIcon.On)
        icon7.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Disabled, QIcon.Off)
        icon7.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Disabled, QIcon.On)
        icon7.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Active, QIcon.Off)
        icon7.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Active, QIcon.On)
        icon7.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Selected, QIcon.Off)
        icon7.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Selected, QIcon.On)
        self.toolBox.addItem(self.page, icon7, u"Hasta Bilgileri")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 133, 643))
        self.verticalLayout_4 = QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.label_3 = QLabel(self.page_2)
        self.label_3.setObjectName(u"label_3")

        self.verticalLayout_4.addWidget(self.label_3)

        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")

        self.verticalLayout_4.addWidget(self.label_4)

        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon8.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Normal, QIcon.On)
        icon8.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Disabled, QIcon.Off)
        icon8.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Active, QIcon.Off)
        icon8.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Selected, QIcon.Off)
        icon8.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Selected, QIcon.On)
        self.toolBox.addItem(self.page_2, icon8, u"G\u00f6r\u00fcnt\u00fc Bilgileri")

        self.verticalLayout_2.addWidget(self.toolBox)


        self.verticalLayout.addWidget(self.widget)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.dockWidget)

        self.menuBar.addAction(self.menuDosya.menuAction())
        self.menuBar.addAction(self.menuD_zenle.menuAction())
        self.menuBar.addAction(self.menuAyarlar.menuAction())
        self.menuBar.addAction(self.menuPencere.menuAction())
        self.menuDosya.addAction(self.actionA)
        self.menuDosya.addAction(self.actionA_2)
        self.menuDosya.addAction(self.actionSon_Dosyalar)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionLKaydet)
        self.menuDosya.addAction(self.actionFarkl_Kaydet)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionYazd_r)
        self.menuDosya.addAction(self.actionResmi_Kaydet)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionKapat)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.action_k)
        self.DosyaToolBar.addAction(self.actionNew)
        self.DosyaToolBar.addAction(self.actionOpen)
        self.DosyaToolBar.addAction(self.actionSave)
        self.DosyaToolBar_2.addAction(self.actionSend_Back)
        self.DosyaToolBar_2.addAction(self.actionBring_Front)

        self.retranslateUi(MainWindow)

        self.toolBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionA.setText(QCoreApplication.translate("MainWindow", u"Yeni", None))
        self.actionA_2.setText(QCoreApplication.translate("MainWindow", u"A\u00e7", None))
        self.actionSon_Dosyalar.setText(QCoreApplication.translate("MainWindow", u"Son Dosyalar", None))
        self.actionLKaydet.setText(QCoreApplication.translate("MainWindow", u"Kaydet", None))
        self.actionFarkl_Kaydet.setText(QCoreApplication.translate("MainWindow", u"Farkl\u0131 Kaydet", None))
        self.actionYazd_r.setText(QCoreApplication.translate("MainWindow", u"Yazd\u0131r", None))
        self.actionResmi_Kaydet.setText(QCoreApplication.translate("MainWindow", u"Resmi Kaydet", None))
        self.actionKapat.setText(QCoreApplication.translate("MainWindow", u"Kapat", None))
        self.action_k.setText(QCoreApplication.translate("MainWindow", u"\u00c7\u0131k", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"New", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("MainWindow", u"Open", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
        self.actionSend_Back.setText(QCoreApplication.translate("MainWindow", u"Send_Back", None))
#if QT_CONFIG(tooltip)
        self.actionSend_Back.setToolTip(QCoreApplication.translate("MainWindow", u"Send_Back", None))
#endif // QT_CONFIG(tooltip)
        self.actionBring_Front.setText(QCoreApplication.translate("MainWindow", u"Bring_Front", None))
#if QT_CONFIG(tooltip)
        self.actionBring_Front.setToolTip(QCoreApplication.translate("MainWindow", u"Bring_Front", None))
#endif // QT_CONFIG(tooltip)
        self.actionTarama.setText(QCoreApplication.translate("MainWindow", u"Tarama", None))
        self.menuDosya.setTitle(QCoreApplication.translate("MainWindow", u"Dosya", None))
        self.menuD_zenle.setTitle(QCoreApplication.translate("MainWindow", u"D\u00fczenle", None))
        self.menuAyarlar.setTitle(QCoreApplication.translate("MainWindow", u"Ayarlar", None))
        self.menuPencere.setTitle(QCoreApplication.translate("MainWindow", u"Pencere", None))
        self.DosyaToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.DosyaToolBar_2.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_2", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"G\u00f6r\u00fcnt\u00fc Bilgileri", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Bilgiler", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Bilgiler2", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("MainWindow", u"Hasta Bilgileri", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Bilgiler3", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"bilgiler4", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", u"G\u00f6r\u00fcnt\u00fc Bilgileri", None))
    # retranslateUi

